### ISSUE TITLE
Color levels are shifted for one position

### ISSUE THREAD

**Issue by michaelsjackson** [alphapapa/org-graph-view#2]
I just recognized colors in org-mode and the graph are not matching, shifted by one level, rechecked in your demo gif, same there. Just wanted to report quickly here.

**Comment by alphapapa** [comment]
Thanks, please let me know if that takes care of it.

**Comment by michaelsjackson** [comment]
Thanks, wonderful, now colors are matching. Greetings!

**Comment by alphapapa** [comment]
:)  If you like colors, you might find this interesting: https://github.com/alphapapa/prism.el

**Comment by michaelsjackson** [comment]
Thanks for the tip, I will check it, yes colors can be fine. 
The theme I am using currently is `(require 'moe-theme)
(moe-light)`

However after applying the color level correction the top level fonts are a bit bigger, thus distorting the rectangular presentation, I guess only because of this I will switch back to the wrong colors, because then all fonts have same (smaller) size.  Another solution to this problem could be if the rectangular representation could have more spaces inbetween, two or more, now there is only one space as gap, I guess.

**Comment by alphapapa** [comment]
Well, probably the thing to do is allow the face height to be fixed, for users who have varying heights per level (like us).  Shouldn't be too hard.  Remind me if I forget...  :)

**Comment by alphapapa** [comment]
This has been obsoleted by the new code that uses Graphviz.  Check it out!  :)

**Comment by michaelsjackson** [comment]
Thanks for the hint, after the first error, which is a different one, I should give up, I guess it is again related to emacs-25.3 ...

`Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 3) 4)
  color-rgb-to-hex(0.37254901960784315 0.6862745098039216 0.8431372549019608 2)
  (let* ((--dash-source-56-- input0) (r (car-safe (prog1 --dash-source-56-- (setq --dash-source-56-- (cdr --dash-source-56--))))) (g (car-safe (prog1 --dash-source-56-- (setq --dash-source-56-- (cdr --dash-source-56--))))) (b (car --dash-source-56--))) (color-rgb-to-hex r g b 2))
`

**Comment by alphapapa** [comment]
Yes, it seems that that function only accepted 3 arguments back then.

**Comment by michaelsjackson** [comment]
Thanks for the turbo quick response, no problem, I also like the old-school text variant, maybe you should not remove this version, just add the new style, so users can have both, one for text style, and this new svg for emacs 26 users.

There is also org-mind-map-write, similar to yours, only not clickable, yours would have additionally colors and clicks. I have now 3 visual variants:
- org-brain (text style)
- org-mind-map-write (graphviz, pdf, svg and more output formats)
- org-graph-view (text style)

**Comment by alphapapa** [comment]
I'll consider keeping the text variant, especially if there are any unresolved issues with using Graphviz/SVG.  But if I'm able to fix all of those issues, it probably won't be worth having both implementations in the code.

Thanks for all of your feedback.
