### ISSUE TITLE
How to start with this? :)

### ISSUE THREAD

**Issue by AtomicNess123** [alphapapa/org-graph-view#9]
I place my cursor on an ORGMODE file, do `M-x org-graph-view`, and nothing happens :(

**Comment by enisozgen** [comment]
Can you run M-x `toggle-debug-on-error` and try again. This can give some output for you.

**Comment by AtomicNess123** [comment]
Where should my cursor be? When I am on top of the org file (above #+TITLE), I get the message: "Cannot move further up".
When I try another org file without TITLE, I get

![image](https://user-images.githubusercontent.com/47029233/117544360-c75f6e80-b029-11eb-91c6-ce23f7ebc8a6.png)

**Comment by enisozgen** [comment]
Honestly, I don't use org-graph-view yet. Couldn't find time to integrate it to my configuration. 

I just wanted to show some way for you since there was not so much info in your issue. 

Sure anyone has more info will help better. 

Regards

**Comment by alphapapa** [comment]
I just tested in a clean Emacs configuration and it works for me on Emacs 26.3.

1.  `emacs -q` (I actually use https://github.com/alphapapa/emacs-sandbox.sh).
2. Install `dash` and `s` (the sandbox script makes this much easier than having to setup the package system over again).
3. Eval `(require 'org-element)` (maybe necessary depending on Emacs/Org version; can be fixed sometime).
3. Open `org-graph-view.el` in a buffer and `eval-buffer`.
4. Open an Org file (I use https://github.com/alphapapa/org-rifle/blob/master/test/data.org) and `M-x org-graph-view RET`.
5.  Works for me.

Anyway, if you can find bugs to be fixed, please let me know, but keep in mind that this is mostly a prototype at this point.  I may package it in the future, but it needs more work before being published (your help finding bugs is appreciated).

**Comment by AtomicNess123** [comment]
Thanks a lot! This is what I get:
![image](https://user-images.githubusercontent.com/47029233/120750821-acd8c200-c50f-11eb-92db-12467538cfc4.png)

**Comment by alphapapa** [comment]
Yeah, you'll need one that is.  Future versions of Emacs or this package might not require that.

**Comment by AtomicNess123** [comment]
Is there a way I can get it to work, can I install ImageMagick SVG support?

**Comment by alphapapa** [comment]
Please use your search engine of choice to find out about getting a build of Emacs with ImageMagick support.  I can't help you with that myself.
